### ISSUE TITLE
x_test, y_test in run_attack.py(line 54) is not defined

### ISSUE THREAD

**Issue by wenjie710** [fra31/sparse-imperceivable-attacks#1]
Thanks for sharing the code. Where is the definition of x_test, y_test in run_attack.py(line 54)?

**Comment by fra31** [comment]
Hi, at the moment the datasets are not in the repository.

However, you can get them from [https://github.com/fra31/fab-attack/tree/master/datasets](https://github.com/fra31/fab-attack/tree/master/datasets).

Then you can add this function to `run_attack.py`

```
def load_dataset(dataset):
  if dataset == 'mnist':
    mnist_data = scipy.io.loadmat("datasets/mnist/mnist_test.mat")
    x_test = mnist_data['X_test']
    x_test = np.expand_dims(x_test,3)
    y_test = mnist_data['label_test']
    y_test_0 = np.squeeze(y_test)
    
   elif dataset == 'cifar10':
    cifar10_data = scipy.io.loadmat("datasets/cifar10/cifar10_test.mat")
    x_test = cifar10_data['Xtest']
    y_test = cifar10_data['Ytest']
    y_test_0 = np.squeeze(y_test)
    
  else:
    raise ValueError('unknown dataset')
    
  return x_test, y_test_0
```

and then
```
x_test, y_test = load_dataset(hps.dataset)
```
around [here](https://github.com/fra31/sparse-imperceivable-attacks/blob/74610132171755d013cbed99598b989e5c89d9ea/run_attack.py#L37).
In this way the full test set is loaded (images and labels).

Let me know if it works!

**Comment by fra31** [comment]
Added [here](https://github.com/fra31/sparse-imperceivable-attacks/blob/408d7cfc6c69b5686770d23927d3f2aea723f2e5/run_attack.py#L41) now.
